version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: fonteyn-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  web:
    build: .
    container_name: fonteyn-hrm
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data: