name: Trigger auto deployment for hrmapp

on:
  push:
    branches:
      [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC (optional but included)
      contents: read # Required for repository access

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.HRMAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HRMAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HRMAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: fentaka.azurecr.io
          registryUsername: ${{ secrets.HRMAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HRMAPP_REGISTRY_PASSWORD }}
          containerAppName: hrmapp
          resourceGroup: Fonteyn_Holiday_Park
          imageToBuild: fentaka.azurecr.io/hrmazure:${{ github.sha }}
